### ISSUE TITLE
Please add a screen shot

### ISSUE THREAD

**Issue by unixorn** [mdan16/cf-ps1#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots so that users can see what they look like without having to install them.

Thanks!

**Comment by mdan16** [comment]
@unixorn It's a good idea! I added a screen shot of prompt. https://github.com/mdan16/cf-ps1/pull/2

Thanks!
